[package]
name = "spedesunu"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
toml = "0.8.19"
walkdir = "2.5.0"
